sudo: false
language: node_js
cache:
  yarn: true
notifications:
  email: false
node_js:
  - '8'
before_install:
  - yarn global add codecov
script:
  - yarn run lint
  - yarn run lint-docs
  - yarn run test-node
  - yarn run cover
  - codecov
after_success:
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
